import {
  isAddressValid,
  isEmailValid,
  isFirstNameValid,
  isIDValid,
  isLastNameValid,
  isMobileValid,
  isPasswordConfirmValid,
  isPasswordValid,
} from "./validation";

export const REGISTER_FIELDS = [
  {
    label: "ID Card",
    id: "IDcard",
    type: "number",
    placeholder: "ID Card",
    validator: isIDValid,
    help: "An israeli ID card.",
  },
  {
    label: "Password",
    id: "password",
    type: "password",
    placeholder: "Password",
    validator: isPasswordValid,
    help: "6-12 characters. At least one lowercase, one uppercase, one digit, one of #?!@$ %^&*- .",
  },
  {
    label: "Confirm Password",
    id: "passwordConfirm",
    type: "password",
    placeholder: "Confirm Password",
    validator: isPasswordConfirmValid,
  },
  {
    label: "First Name",
    id: "firstName",
    type: "text",
    autoComplete: "given-name",
    placeholder: "First Name",
    validator: isFirstNameValid,
    help: "must contain between 5-32 characters.",
  },
  {
    label: "Last Name",
    id: "lastName",
    type: "text",
    autoComplete: "family-name",
    placeholder: "Last Name",
    validator: isLastNameValid,
    help: "must contain between 5-32 characters.",
  },
  {
    label: "Email",
    id: "email",
    type: "email",
    autoComplete: "email",
    placeholder: "Email",
    validator: isEmailValid,
  },
  {
    label: "Mobile",
    id: "mobile",
    type: "number",
    placeholder: "Mobile",
    validator: isMobileValid,
    help: "An israeli mobile number.",
  },
  {
    label: "City",
    id: "city",
    type: "text",
    placeholder: "City",
    validator: isAddressValid,
  },
  {
    label: "Street",
    id: "street",
    type: "text",
    placeholder: "Street",
    validator: isAddressValid,
  },
];
